name: Run end2end tests

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Url to dss instance where tests will run'
        required: true
        default: https://tests-integration.solutions.dataiku-dss.io/
      cookie:
        description: 'Cookie to authenticate to webapp'
        required: true
      webapp_run_id:
        description: 'Webapp instance to use during the tests'
        required: true

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  end2end-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Run tests
      env:
        DKU_DSS_URL: ${{ inputs.url }}
        DKU_API_KEY: ${{ secrets.tests_integrations_api_key }}
        DKU_WEBAPP_RUN_ID: ${{ inputs.webapp_run_id }}
        DKU_WEBAPP_COOKIE: ${{ inputs.cookie }}
      run: |
        python -m pip install --upgrade pip
        cd dss-plugin-visual-edit/tests/end2end
        pip install -r requirements.txt
        behave --no-logcapture --logging-level=ERROR

